DROP PROCEDURE IF EXISTS dbo.spProgramAddUpdate
GO
DROP PROCEDURE IF EXISTS dbo.spProgramGetAll
GO
DROP PROCEDURE IF EXISTS dbo.spProgramGetById
GO
DROP PROCEDURE IF EXISTS dbo.spProgramNameExists
GO
DROP PROCEDURE IF EXISTS dbo.spSessionAddUpdate
GO
DROP PROCEDURE IF EXISTS dbo.spSessionGetAll
GO
DROP PROCEDURE IF EXISTS dbo.spSessionGetById
GO
DROP PROCEDURE IF EXISTS dbo.spSessionInactivate
GO
DROP PROCEDURE IF EXISTS dbo.spSessionNameExists
GO
