@rootUrl= https://localhost:7270

GET {{rootUrl}}/programs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYmE5YjFkNi03NGY1LTRkYzUtYWRhYS0wZGNmNDRhMTkzYmMiLCJnaXZlbl9uYW1lIjoianVsaWUiLCJmYW1pbHlfbmFtZSI6ImxldnkiLCJqdGkiOiI4MDhlNGM3NS1kMGI4LTQ1ZjgtODgxZi03YWRkOWUzY2RhYTEiLCJleHAiOjE3MDM3OTIxNDAsImlzcyI6IkJiZ0VkdWNhdGlvbiIsImF1ZCI6IkJiZ0VkdWNhdGlvbiJ9.4Z55iwLGy5gK0E7Dq3x-mkiaCO5CpM6IrWcFkGgnbts
